# Use the file format compatible with Docker Compose 3.8
version: "3.8"

# Each thing that Docker Compose runs is referred to as
# a "service". In our case, our Rails application is one
# service ("web") and our PostgreSQL database instance
# is another service ("database").
services:
  postgres:
    # Use the postgres 11.5 base image for this container.
    image: postgres:11.5

    volumes:
      # We need to tell Docker where on the PostgreSQL
      # container we want to keep the PostgreSQL data.
      # In this case we're telling it to use a directory
      # called /var/lib/postgresql/data, although it
      # conceivably could have been something else.
      #
      # We're associating this directory with something
      # called a volume. (You can see all your Docker
      # volumes by running +docker volume ls+.) The name
      # of our volume is postgres.
      - postgres:/var/lib/postgresql/data

      # This copies our init.sql into our container, to
      # a special file called
      # /docker-entrypoint-initdb.d/init.sql. Anything
      # at this location will get executed one per
      # container, i.e. it will get executed the first
      # time the container is created but not again.
      #
      # The init.sql file is a one-line that creates a
      # user called (arbitrarily) boats_development.
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - './redis:/data'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile.sidekiq
    command: bundle exec sidekiq
    volumes:
      - '.:/code'
    working_dir: /code
    environment:
      REDIS_URL_SIDEKIQ: redis://redis:6379/1
      DATABASE_URL: postgres://postgres@postgres


  web:
    # The root directory from which we're building.
    build:
      context: .
      dockerfile: Dockerfile.web

    # This makes it so any code changes inside the project
    # directory get synced with Docker. Without this line,
    # we'd have to restart the container every time we
    # changed a file.
    volumes:
      - .:/code:cached
    
    # The command to be run when we run "docker-compose up".
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

    # Expose port 3000.
    ports:
      - "3000:3000"

    # Specify that this container depends on the other
    # container which we've called "database".
    depends_on:
      - postgres
      - sidekiq
      - redis

    # Specify the values of the environment variables
    # used in this container.
    environment:
      RAILS_ENV: development
      DATABASE_NAME: codejudge
      DATABASE_USER: codejudge
      DATABASE_PASSWORD:
      DATABASE_HOST: postgres
      REDIS_URL_SIDEKIQ: redis://redis:6379/1

  cable:
    depends_on:
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile.web
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - '.:/code'
    env_file:
      - '.env'

# Declare the volumes that our application uses.
volumes:
  postgres:
  redis:
